/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GradientButton {
    }
}
export interface GradientButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGradientButtonElement;
}
declare global {
    interface HTMLGradientButtonElement extends Components.GradientButton, HTMLStencilElement {
    }
    var HTMLGradientButtonElement: {
        prototype: HTMLGradientButtonElement;
        new (): HTMLGradientButtonElement;
    };
    interface HTMLElementTagNameMap {
        "gradient-button": HTMLGradientButtonElement;
    }
}
declare namespace LocalJSX {
    interface GradientButton {
        "onGradientButtonClick"?: (event: GradientButtonCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "gradient-button": GradientButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gradient-button": LocalJSX.GradientButton & JSXBase.HTMLAttributes<HTMLGradientButtonElement>;
        }
    }
}
